name: Waka Time

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Waka-Time:
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements.txt
          check-latest: true

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update status
        run: python main.py
